import { defineConfig } from 'vitest/config';
import { resolve } from 'path';

export default defineConfig({
  test: {
    globals: true,
    environment: 'node',
    setupFiles: ['./tests/setup/global.js'],
    coverage: {
      provider: 'v8',
      reporter: ['text', 'json', 'html', 'lcov'],
      exclude: [
        'node_modules/**',
        'tests/**',
        'app/generated/**',
        'app/prisma/migrations/**',
        'workers/**',
        'nginx/**',
      ],
      thresholds: {
        lines: 70,
        functions: 70,
        branches: 60,
        statements: 70,
      },
    },
    testTimeout: 10000,
    hookTimeout: 10000,
    reporters: ['verbose'],
  },
  resolve: {
    alias: {
      '#utils/index.js':    resolve('./app/utils/index.js'),
      '#utils/logger.js':   resolve('./app/utils/logger.js'),
      '#utils/response.js': resolve('./app/utils/response.js'),
      '#utils/error.js':    resolve('./app/utils/error.js'),
      '#utils/jwt.js':      resolve('./app/utils/jwt.js'),
      '#utils/hashPassword.js': resolve('./app/utils/hashPassword.js'),
      '#utils/token.util.js':   resolve('./app/utils/token.util.js'),
      '#utils':             resolve('./app/utils'),
      '#config/redis.js':   resolve('./app/config/redis.js'),
      '#config/rabbitmq.js':resolve('./app/config/rabbitmq.js'),
      '#config/storageConfig.js': resolve('./app/config/storageConfig.js'),
      '#config/cloudinary.config.js': resolve('./app/config/cloudinary.config.js'),
      '#config':            resolve('./app/config'),
      '#controllers/admin/author.controller.js': resolve('./app/controllers/admin/author.controller.js'),
      '#controllers/admin/book.controller.js':   resolve('./app/controllers/admin/book.controller.js'),
      '#controllers/admin/genre.controller.js':  resolve('./app/controllers/admin/genre.controller.js'),
      '#controllers/admin/user.controller.js':   resolve('./app/controllers/admin/user.controller.js'),
      '#controllers/admin/recommendation.controller.js': resolve('./app/controllers/admin/recommendation.controller.js'),
      '#controllers/admin/dashboard.controller.js': resolve('./app/controllers/admin/dashboard.controller.js'),
      '#controllers/auth/auth.controller.js':    resolve('./app/controllers/auth/auth.controller.js'),
      '#controllers/auth/token.controller.js':   resolve('./app/controllers/auth/token.controller.js'),
      '#controllers/auth/password-reset.controller.js': resolve('./app/controllers/auth/password-reset.controller.js'),
      '#controllers/auth/activate-account.controller.js': resolve('./app/controllers/auth/activate-account.controller.js'),
      '#controllers/user/book.controller.js':    resolve('./app/controllers/user/book.controller.js'),
      '#controllers/user/rating.controller.js':  resolve('./app/controllers/user/rating.controller.js'),
      '#controllers/user/favorite.controller.js': resolve('./app/controllers/user/favorite.controller.js'),
      '#controllers/user/bookmark.controller.js': resolve('./app/controllers/user/bookmark.controller.js'),
      '#controllers/user/history.controller.js': resolve('./app/controllers/user/history.controller.js'),
      '#controllers/user/profile.controller.js': resolve('./app/controllers/user/profile.controller.js'),
      '#controllers/user/recommendation.controller.js': resolve('./app/controllers/user/recommendation.controller.js'),
      '#controllers/user/genre.controller.js':   resolve('./app/controllers/user/genre.controller.js'),
      '#controllers':       resolve('./app/controllers'),
      '#services/auth.service.js':        resolve('./app/services/auth.service.js'),
      '#services/book.service.js':        resolve('./app/services/book.service.js'),
      '#services/user.service.js':        resolve('./app/services/user.service.js'),
      '#services/genre.service.js':       resolve('./app/services/genre.service.js'),
      '#services/rating.service.js':      resolve('./app/services/rating.service.js'),
      '#services/favorite.service.js':    resolve('./app/services/favorite.service.js'),
      '#services/bookmark.service.js':    resolve('./app/services/bookmark.service.js'),
      '#services/history.service.js':     resolve('./app/services/history.service.js'),
      '#services/email.service.js':       resolve('./app/services/email.service.js'),
      '#services/recommendation.service.js': resolve('./app/services/recommendation.service.js'),
      '#services/session-store.service.js':  resolve('./app/services/session-store.service.js'),
      '#services/storage.service.js':        resolve('./app/services/storage.service.js'),
      '#services/activate-account.service.js': resolve('./app/services/activate-account.service.js'),
      '#services/password-reset.service.js':   resolve('./app/services/password-reset.service.js'),
      '#services/dashboard.service.js':   resolve('./app/services/dashboard.service.js'),
      '#services/author.service.js':      resolve('./app/services/author.service.js'),
      '#services':          resolve('./app/services'),
      '#middlewares/authenticateToken.js':  resolve('./app/middlewares/authenticateToken.js'),
      '#middlewares/authorize.middleware.js': resolve('./app/middlewares/authorize.middleware.js'),
      '#middlewares/validation.middleware.js': resolve('./app/middlewares/validation.middleware.js'),
      '#middlewares/rateLimit.middleware.js': resolve('./app/middlewares/rateLimit.middleware.js'),
      '#middlewares/upload.middleware.js':   resolve('./app/middlewares/upload.middleware.js'),
      '#middlewares/errorHandler.js':       resolve('./app/middlewares/errorHandler.js'),
      '#middlewares':       resolve('./app/middlewares'),
      '#routes/index.js':   resolve('./app/routes/index.js'),
      '#routes/auth/auth.routes.js':        resolve('./app/routes/auth/auth.routes.js'),
      '#routes/user/book.routes.js':        resolve('./app/routes/user/book.routes.js'),
      '#routes/user/genre.routes.js':       resolve('./app/routes/user/genre.routes.js'),
      '#routes/user/bookmark.routes.js':    resolve('./app/routes/user/bookmark.routes.js'),
      '#routes/user/history.routes.js':     resolve('./app/routes/user/history.routes.js'),
      '#routes/user/profile.routes.js':     resolve('./app/routes/user/profile.routes.js'),
      '#routes/user/rating.routes.js':      resolve('./app/routes/user/rating.routes.js'),
      '#routes/user/favorite.routes.js':    resolve('./app/routes/user/favorite.routes.js'),
      '#routes/user/recommendation.routes.js': resolve('./app/routes/user/recommendation.routes.js'),
      '#routes/admin/book.routes.js':       resolve('./app/routes/admin/book.routes.js'),
      '#routes/admin/genre.routes.js':      resolve('./app/routes/admin/genre.routes.js'),
      '#routes/admin/user.routes.js':       resolve('./app/routes/admin/user.routes.js'),
      '#routes/admin/author.routes.js':     resolve('./app/routes/admin/author.routes.js'),
      '#routes/admin/dashboard.routes.js':  resolve('./app/routes/admin/dashboard.routes.js'),
      '#routes/admin/recommendation.routes.js': resolve('./app/routes/admin/recommendation.routes.js'),
      '#routes':            resolve('./app/routes'),
      '#validators/auth.validator.js':      resolve('./app/validators/auth.validator.js'),
      '#validators/book.validator.js':      resolve('./app/validators/book.validator.js'),
      '#validators/admin.validator.js':     resolve('./app/validators/admin.validator.js'),
      '#validators/bookmark.validator.js':  resolve('./app/validators/bookmark.validator.js'),
      '#validators/interaction.validator.js': resolve('./app/validators/interaction.validator.js'),
      '#validators/genre.validator.js':     resolve('./app/validators/genre.validator.js'),
      '#validators/user.validator.js':      resolve('./app/validators/user.validator.js'),
      '#validators/pattern.js':            resolve('./app/validators/pattern.js'),
      '#validators':        resolve('./app/validators'),
      '#mappers/book.mapper.js':    resolve('./app/mappers/book.mapper.js'),
      '#mappers/user.mapper.js':    resolve('./app/mappers/user.mapper.js'),
      '#mappers/genre.mapper.js':   resolve('./app/mappers/genre.mapper.js'),
      '#mappers/rating.mapper.js':  resolve('./app/mappers/rating.mapper.js'),
      '#mappers/favorite.mapper.js': resolve('./app/mappers/favorite.mapper.js'),
      '#mappers/bookmark.mapper.js': resolve('./app/mappers/bookmark.mapper.js'),
      '#mappers/history.mapper.js':  resolve('./app/mappers/history.mapper.js'),
      '#mappers':           resolve('./app/mappers'),
      '#lib/prisma.js':     resolve('./app/lib/prisma.js'),
      '#lib':               resolve('./app/lib'),
      '#constants/roles.js':       resolve('./app/constants/roles.js'),
      '#constants/tokenTypes.js':  resolve('./app/constants/tokenTypes.js'),
      '#constants':         resolve('./app/constants'),
      '#publishers/recommendation.publisher.js': resolve('./app/publishers/recommendation.publisher.js'),
      '#publishers':        resolve('./app/publishers'),
    },
  },
});